Chain extension
Polkadot-Blockchain-Academy/Academy-PoW pull request #33
Opened 2023-07-05 13:53 UTC by fbielejec

2023-07-05 17:41 UTC, JoshOrndorff commented
Looks interesting. Please add a description with some context when you are ready.

2023-07-06 06:03 UTC, pmikolajczyk41 requested changes

2023-07-06 06:03 UTC, pmikolajczyk41 commented on runtime/src/chain_extension.rs
> +            RANDOM_FUNCTION_OK
RANDOM_FUNCTION_ID

2023-07-06 06:03 UTC, pmikolajczyk41 commented on runtime/src/chain_extension.rs
> +        let random_seed = RandomnessCollectiveFlip::random(&arg).0;
you are missing charging appropriate amount of gas - unfortunately for chain extensions we have to do it manually; i guess that taking corresponding weight from pallet rcf should be fine

2023-07-18 22:12 UTC, JoshOrndorff approved these changes
I'm fine with this whenever @pmikolajczyk41 and @fbielejec think it is good enough. I'm not qualified to review it technically.

2024-01-02 17:19 UTC, JoshOrndorff commented
Closing this because we will not run contracts on the pow network this time.

2024-01-02 17:19 UTC, closed without merging